version: '3.1'
services:
  elasticsearchapp:
    environment:
      - discovery.type=single-node
    build: ./elasticsearch_app
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - my_network
    volumes:
      - ./elasticsearch_app/data:/usr/share/elasticsearch/data
  springbootapp:
    build: ./springboot_app
    ports:
      - '8080:8080'
    networks:
      - my_network
    volumes:
      - ./springboot_app/springboot-elasticsearch:/home/springboot-elasticsearch
    depends_on:
      - elasticsearchapp
  reactapp:
    build: ./react_apps
    ports:
      - '80:3000'
    networks:
      - my_network
    volumes:
      - ./react_apps/react_app:/react_app
networks:
  my_network:  # Uygulama konteynerleri arasında bir ağ oluşturur
    driver: bridge